language: csharp
solution: Unosquare.Labs.EmbedIO.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
matrix:
  include:
    - os: linux
      mono: latest
      sudo: required
    - os: linux
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
      dist: trusty
      sudo: false
    - os: osx
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
    - os: osx
      mono: latest
install:
  - if [[ $DOTNETCORE == "1" ]]; then dotnet restore; else nuget restore Unosquare.Labs.EmbedIO.Lib.sln; fi
  - if [[ $DOTNETCORE == "" ]]; then nuget install NUnit.ConsoleRunner -OutputDirectory testrunner; fi
before_script:
  - if [[ $DOTNETCORE == "" ]]; then export LD_LIBRARY_PATH=/usr/local/lib; fi
script:
  - if [[ $DOTNETCORE == "" ]]; then xbuild Unosquare.Labs.EmbedIO.Lib.sln /p:"TargetFrameworkVersion=v4.5;Configuration=Release"; else dotnet test ./test/Unosquare.Labs.EmbedIO.Tests -f netcoreapp1.1; fi
  - if [[ $DOTNETCORE == "" ]]; then mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./test/Unosquare.Labs.EmbedIO.Tests/bin/Release/Unosquare.Labs.EmbedIO.Tests.dll; fi
