language: csharp
solution: Unosquare.Labs.EmbedIO.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
mono:
  - latest
  - 4.2.1
install:
  - nuget restore Unosquare.Labs.EmbedIO.Lib.sln
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
  - nuget install coveralls.net -Version 0.6.0 -OutputDirectory coveralls
  - sudo apt-get install gtk-sharp2
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.6.4.nupkg > /tmp/mono.cecil.0.9.6.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.6.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../unosquare/monocov
  - cd ../../unosquare/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  - cd ../../unosquare/embedio
script:
  - xbuild  Unosquare.Labs.EmbedIO.Lib.sln /p:"TargetFrameworkVersion=v4.5;Configuration=Release"
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export MONO_IOMAP=all
  - mono --debug --profile=monocov:outfile=monocovCoverage.cov,+[Unosquare.Labs.EmbedIO] ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe --process=Single ./test/Unosquare.Labs.EmbedIO.Tests/bin/Release/Unosquare.Labs.EmbedIO.Tests.dll
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - mono ./coveralls/coveralls.net.0.6.0/tools/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --repoToken wB56cdByaIbXNGH3VeniQ1XC7NiuT5cqd --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci  --useRelativePaths
