version: '1.13.{build}'
image: 
- Visual Studio 2017
- Ubuntu
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:  
       secure: 1Ce1wX4c2duHsRshiJRZFVIe6VI/r0WTAUG/tXuGFue9CmTI13NJRgZbl9irVKBA
  op_build_user: "Geo Perez"
  op_build_user_email: "geovanni.perez@gmail.com"
  access_token:
       secure: HzWdswNyfQbQ0vLk9IQyO+Ei9mxoPYp9rvv6HPhtC9J/Fm7EHRzyV953pbPRXI9I
before_build:
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y --no-progress
        }
- dotnet restore --verbosity q
- cmd: mkdir tools
- cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- cmd: nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
- ps: | 
        $date_now = Get-Date
        $cert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname localhost -notafter $date_now
        $certThumb = $cert.Thumbprint
        $guid = [guid]::NewGuid()
        $command = "http add sslcert ipport=0.0.0.0:5555 certhash=$certThumb appid={$guid}"
        $command | netsh
build_script:
- cmd: msbuild /verbosity:quiet /p:Configuration=Release Unosquare.Labs.EmbedIO.sln
- cmd: | 
      cd src/EmbedIO.Forms.Sample/
      msbuild /t:restore EmbedIO.Forms.Sample.sln
      msbuild /verbosity:quiet /p:Configuration=Release EmbedIO.Forms.Sample.sln
      cd ..
      cd ..
- sh: |
        cd src/Unosquare.Labs.EmbedIO
        msbuild /verbosity:quiet /p:Configuration=Release;TargetFrameworks="netstandard2.0;netstandard1.3" 
        cd ..
        cd ..
        pwd
test_script:
- dotnet test test/Unosquare.Labs.EmbedIO.Tests/Unosquare.Labs.EmbedIO.Tests.csproj -c Release -f netcoreapp2.2
- cmd: dotnet test test\Unosquare.Labs.EmbedIO.Tests\Unosquare.Labs.EmbedIO.Tests.csproj -c Release -f net472
- cmd: dotnet test test\Unosquare.Labs.EmbedIO.Tests\Unosquare.Labs.EmbedIO.Tests.csproj -c Release -f net452
- cmd: tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"%ProgramFiles%\dotnet\dotnet.exe" -targetargs:"test test\Unosquare.Labs.EmbedIO.Tests\Unosquare.Labs.EmbedIO.Tests.csproj -c Release -f net452" -output:coverage.xml -filter:"+[Unosquare.Labs.EmbedIO*]* -[Unosquare.Labs.EmbedIO.Test*]*" -register:userdotnet
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --serviceName appveyor --jobId $Env:APPVEYOR_BUILD_NUMBER
        }
after_build:
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            git config --global core.autocrlf false 
            git config --global user.email $env:op_build_user_email
            git config --global user.name $env:op_build_user
            git clone -b documentation https://github.com/unosquare/best-practices.git -q            
            git clone https://github.com/unosquare/embedio.wiki.git wiki -q
            docfx docfx.json --logLevel Error
            git clone https://github.com/unosquare/embedio.git -b gh-pages origin_site -q
            Copy-Item origin_site/.git _site -recurse
            CD _site
            Copy-Item README.html index.html -force
            git add -A 2>&1
            git commit -m "Documentation update" -q
            git push origin gh-pages -q
            CD ..
        }
